# Generated by Django 4.2.23 on 2026-04-02 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_patients', models.IntegerField(default=0)),
                ('admitted_patients', models.IntegerField(default=0)),
                ('critical_cases', models.IntegerField(default=0)),
                ('lab_tests_performed', models.IntegerField(default=0)),
                ('pharmacy_orders', models.IntegerField(default=0)),
                ('patient_growth_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('insurance_claims_processed', models.IntegerField(default=0)),
                ('average_transaction_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
