# Generated by Django 5.2.12 on 2026-04-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalmetric',
            name='voice_bookings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clinicalmetric',
            name='web_bookings',
            field=models.IntegerField(default=0),
        ),
    ]
