# Generated by Django 4.2.23 on 2026-04-02 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='category name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'inventory category',
                'verbose_name_plural': 'inventory categories',
                'db_table': 'hospital_inventory_categories',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='item name')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU / System Identifier')),
                ('unit', models.CharField(choices=[('units', 'Units'), ('boxes', 'Boxes'), ('packs', 'Packs'), ('liters', 'Liters'), ('mg', 'Milligrams')], default='units', max_length=20, verbose_name='measurement unit')),
                ('current_stock', models.PositiveIntegerField(default=0, verbose_name='current stock level')),
                ('min_stock_level', models.PositiveIntegerField(default=10, verbose_name='minimum stock threshold')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='unit price (PKR)')),
                ('supplier_info', models.TextField(blank=True, verbose_name='supplier intelligence')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='physical storage node')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(help_text='The thematic category for this resource shard.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorycategory')),
            ],
            options={
                'verbose_name': 'inventory item',
                'verbose_name_plural': 'inventory items',
                'db_table': 'hospital_inventory_items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'Restock / Inward'), ('out', 'Allocation / Outward'), ('adj', 'Manual Adjustment')], max_length=10)),
                ('quantity', models.IntegerField(verbose_name='quantity shard')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='allocation reason')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.inventoryitem')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'stock log',
                'verbose_name_plural': 'stock logs',
                'db_table': 'hospital_inventory_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
