# Generated by Django 4.2.23 on 2026-04-02 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0003_doctor_clinic_address_doctor_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='test name')),
                ('category', models.CharField(max_length=100, verbose_name='diagnostic area')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('turnaround_time', models.CharField(help_text='e.g. 24 hours', max_length=50, verbose_name='ETA')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'hospital_lab_tests',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.TextField(blank=True, verbose_name='findings')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='lab_reports/', verbose_name='clinical report (PDF)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('result_date', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor')),
            ],
            options={
                'db_table': 'hospital_lab_results',
                'ordering': ['-test_date'],
            },
        ),
    ]
