# Generated by Django 4.2.23 on 2026-04-19 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patientprofile_father_name_and_more'),
        ('doctors', '0003_doctor_clinic_address_doctor_education'),
        ('lab', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='lab order ID')),
                ('context_type', models.CharField(choices=[('WALKIN', 'Walk-in'), ('APPOINTMENT', 'Appointment'), ('ADMISSION', 'Admission')], default='WALKIN', max_length=20)),
                ('doctor_notes', models.TextField(blank=True, verbose_name='clinical notes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='patients.patientprofile')),
                ('tests', models.ManyToManyField(related_name='orders', to='lab.labtest')),
            ],
            options={
                'db_table': 'hospital_lab_orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
