# Generated by Django 4.2.23 on 2026-04-05 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ward name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='ward code')),
                ('floor', models.IntegerField(default=1, verbose_name='floor level')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='system.department')),
            ],
            options={
                'db_table': 'hospital_system_wards',
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=20, verbose_name='bed number')),
                ('bed_type', models.CharField(choices=[('general', 'General'), ('icu', 'ICU'), ('private', 'Private'), ('emergency', 'Emergency')], default='general', max_length=20)),
                ('is_occupied', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_cleaned', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_bed', to='patients.patientprofile')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='system.ward')),
            ],
            options={
                'db_table': 'hospital_system_beds',
                'unique_together': {('ward', 'bed_number')},
            },
        ),
    ]
