# Generated by Django 4.2.23 on 2026-04-05 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_ward_bed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='department',
        ),
        migrations.DeleteModel(
            name='Bed',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
