# Generated by Django 4.2.23 on 2026-04-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_remove_ward_department_delete_bed_delete_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalalert',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalalert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
