# Generated by Django 5.2.12 on 2026-03-27 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(help_text='The date of the appointment (YYYY-MM-DD).', verbose_name='appointment date')),
                ('start_time', models.TimeField(help_text='Appointment start time (HH:MM).', verbose_name='start time')),
                ('end_time', models.TimeField(help_text='Appointment end time (HH:MM). Set automatically from slot duration.', verbose_name='end time')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the appointment.', max_length=10, verbose_name='status')),
                ('notes', models.TextField(blank=True, default='', help_text="Patient's symptoms, concerns, or reason for visit.", verbose_name='patient notes')),
                ('doctor_notes', models.TextField(blank=True, default='', help_text="Doctor's post-appointment notes. Only visible to doctor and admin.", verbose_name='doctor notes')),
                ('booked_via_voice', models.BooleanField(default=False, help_text='True if this appointment was booked using the AI voice pipeline.', verbose_name='booked via voice')),
                ('cancellation_reason', models.TextField(blank=True, default='', help_text='Reason provided when the appointment was cancelled.', verbose_name='cancellation reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the appointment was booked.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the appointment was last updated.')),
                ('doctor', models.ForeignKey(help_text='The doctor this appointment is with.', on_delete=django.db.models.deletion.PROTECT, related_name='doctor_appointments', to='doctors.doctor')),
                ('patient', models.ForeignKey(help_text='The patient who booked this appointment.', limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'appointment',
                'verbose_name_plural': 'appointments',
                'db_table': 'hospital_appointments',
                'ordering': ['appointment_date', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'appointment_date', 'start_time'), name='unique_doctor_slot', violation_error_message='This doctor already has an appointment at this date and time.')],
            },
        ),
    ]
