# Generated by Django 4.2.23 on 2026-04-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_idempotencykey'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('fully_paid', 'Fully Paid'), ('refunded', 'Refunded')], default='unpaid', help_text='Transaction status of this appointment.', max_length=20, verbose_name='payment status'),
        ),
    ]
