# Generated by Django 4.2.23 on 2026-04-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('in_person', 'In-Person Consultation'), ('telehealth', 'Telehealth/Virtual'), ('follow_up', 'Follow-up Review')], default='in_person', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='priority',
            field=models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent (24h)'), ('emergency', 'Emergency (Immediate)')], default='routine', max_length=15),
        ),
    ]
