# Generated by Django 4.2.23 on 2026-03-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicesession',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
