# Generated by Django 4.2.23 on 2026-03-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0002_voicesession_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicesession',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='voicesession',
            name='guest_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
