# Generated by Django 4.2.23 on 2026-04-02 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Neural Parameter',
            },
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=50, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('intent', models.CharField(max_length=200)),
                ('query', models.TextField()),
                ('resolution', models.CharField(choices=[('Success', 'Resolved Node'), ('Critical-Review', 'High Priority'), ('Access-Denied', 'Authorization Denied'), ('Failure', 'System Failure')], default='Success', max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'AI Conversation Shard',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AISystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('MODEL_LOAD', 'Model Loading'), ('INFERENCE', 'Inference Propagation'), ('THRESHOLD_BREACH', 'Threshold Alert'), ('SECURITY_AUDIT', 'Security Lockdown')], max_length=50)),
                ('status', models.CharField(default='STABLE', max_length=20)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
