# Generated by Django 4.2.23 on 2026-04-19 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0004_room_alter_bed_unique_together_bed_room_and_more'),
        ('finance', '0005_invoice_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='wards.patientadmission'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='context_type',
            field=models.CharField(choices=[('WALKIN', 'Walk-in'), ('APPOINTMENT', 'Appointment'), ('ADMISSION', 'Admission')], default='WALKIN', max_length=20),
        ),
    ]
