# Generated by Django 4.2.23 on 2026-04-02 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0003_doctor_clinic_address_doctor_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, verbose_name='blood group')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('gender', models.CharField(blank=True, max_length=20, verbose_name='gender')),
                ('address', models.TextField(blank=True, verbose_name='physical address')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name='emergency contact')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='emergency contact phone')),
                ('allergies', models.TextField(blank=True, help_text='List of drug/food allergies.', verbose_name='known allergies')),
                ('medical_history', models.TextField(blank=True, help_text='Diabetes, Hypertension, etc.', verbose_name='chronic conditions')),
                ('is_admitted', models.BooleanField(default=False, verbose_name='currently admitted')),
                ('room_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='room number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Associated user account for login.', on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'patient profile',
                'db_table': 'hospital_patient_profiles',
            },
        ),
        migrations.CreateModel(
            name='ClinicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.CharField(max_length=255, verbose_name='primary diagnosis')),
                ('clinical_notes', models.TextField(verbose_name='clinical summary')),
                ('prescription_summary', models.TextField(blank=True, verbose_name='prescription summary')),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('temperature', models.CharField(blank=True, max_length=20)),
                ('heart_rate', models.CharField(blank=True, max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_observations', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'hospital_clinical_records',
                'ordering': ['-observation_date'],
            },
        ),
    ]
