# Generated by Django 4.2.23 on 2026-04-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='current_medications',
            field=models.TextField(blank=True, help_text='List of active medications.', verbose_name='current medications'),
        ),
    ]
