# Generated by Django 4.2.23 on 2026-04-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patientprofile_current_medications'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='mrn',
            field=models.CharField(blank=True, editable=False, help_text='Format: SHI-YYYY-XXXX', max_length=20, verbose_name='medical record number'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='status',
            field=models.CharField(choices=[('complete', 'Verified/Complete'), ('incomplete', 'Quick-Add/Incomplete'), ('archived', 'Archived')], default='incomplete', max_length=15, verbose_name='onboarding status'),
        ),
    ]
