# Generated by Django 4.2.23 on 2026-04-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patientprofile_mrn_patientprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='mrn',
            field=models.CharField(blank=True, editable=False, help_text='Format: SHI-YYYY-XXXX', max_length=20, unique=True, verbose_name='medical record number'),
        ),
    ]
