# Generated by Django 4.2.23 on 2026-04-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patientprofile_mrn'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='age'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='cnic',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNIC'),
        ),
    ]
