# Generated by Django 4.2.23 on 2026-04-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patientprofile_age_patientprofile_cnic'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50, verbose_name='relationship'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='marital_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='marital status'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, verbose_name='occupation'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='preferred_language',
            field=models.CharField(default='English', max_length=50, verbose_name='preferred language'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='privacy_consent',
            field=models.BooleanField(default=False, verbose_name='privacy consent'),
        ),
    ]
