# Generated by Django 4.2.23 on 2026-04-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patientprofile_emergency_contact_relationship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='father/husband name'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='national_id_type',
            field=models.CharField(choices=[('CNIC', 'CNIC'), ('Passport', 'Passport'), ('Other', 'Other')], default='CNIC', max_length=20, verbose_name='ID type'),
        ),
    ]
