# Generated by Django 4.2.23 on 2026-04-18 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patientprofile_emergency_contact_relationship_and_more'),
        ('doctors', '0003_doctor_clinic_address_doctor_education'),
        ('wards', '0002_remove_bed_is_occupied_bed_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('expected_discharge_date', models.DateField(blank=True, null=True)),
                ('actual_discharge_date', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('emergency_room', 'Emergency Room'), ('outpatient', 'Outpatient Department'), ('referral', 'External Referral'), ('transfer', 'Inter-Ward Transfer')], default='outpatient', max_length=20)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('critical', 'Critical')], default='moderate', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active Care'), ('discharged', 'Discharged'), ('transferred', 'Transferred')], default='active', max_length=20)),
                ('primary_diagnosis', models.TextField()),
                ('clinical_notes', models.TextField(blank=True)),
                ('is_emergency', models.BooleanField(default=False)),
                ('admitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_admissions', to='doctors.doctor')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='wards.bed')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='patients.patientprofile')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='wards.ward')),
            ],
            options={
                'verbose_name': 'admission',
                'verbose_name_plural': 'admissions',
                'db_table': 'hospital_clinical_admissions',
                'ordering': ['-admission_date'],
            },
        ),
    ]
