# Generated by Django 4.2.23 on 2026-04-19 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0003_patientadmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, verbose_name='room number')),
                ('room_type', models.CharField(choices=[('general', 'General Ward Room'), ('private', 'Private Suite'), ('icu', 'ICU Cluster'), ('isolation', 'Isolation Unit')], default='general', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='wards.ward')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
                'db_table': 'hospital_clinical_rooms',
                'unique_together': {('ward', 'room_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='wards.room'),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='wards.room'),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('room', 'bed_number')},
        ),
        migrations.RemoveField(
            model_name='bed',
            name='ward',
        ),
    ]
