# Generated by Django 4.2.23 on 2026-04-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('local', 'Local'), ('google', 'Google')], default='local', help_text='Identity stream source for authentication.', max_length=10, verbose_name='authentication provider'),
        ),
    ]
