# Generated by Django 4.2.23 on 2026-04-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_auth_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Designates whether the user has completed the clinical onboarding flow.', verbose_name='onboarding completed'),
        ),
    ]
