# Generated by Django 4.2.23 on 2026-04-18 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cnic',
            field=models.CharField(blank=True, help_text='National Identity Card Number (13 digits). Must be unique for each user.', max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='lock_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_on_all_logins',
            field=models.BooleanField(default=False, help_text='If enabled, receiving an email alert on every successful authentication.', verbose_name='notify on all logins'),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('local', 'Local'), ('google', 'Google'), ('magic_link', 'Magic Link')], default='local', help_text='Identity stream source for authentication.', max_length=10, verbose_name='authentication provider'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Required. Used for clinical alerts and notifications.', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('doctor', 'Doctor'), ('patient', 'Patient'), ('staff', 'Staff')], default='patient', help_text='Determines what the user can access in the system.', max_length=10, verbose_name='role'),
        ),
        migrations.CreateModel(
            name='SecurityOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_otp_registry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(verbose_name='Device Signature (User-Agent)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk (Trusted Device/IP)'), ('MEDIUM', 'Medium Risk (New IP or Device)'), ('HIGH', 'High Risk (Suspicious Pattern)')], default='LOW', max_length=10)),
                ('is_successful', models.BooleanField(default=True)),
                ('user', models.ForeignKey(help_text='Associated user shard.', on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_login_records',
                'ordering': ['-timestamp'],
            },
        ),
    ]
