# Generated by Django 4.2.23 on 2026-04-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='medicine name')),
                ('chemical_formula', models.CharField(blank=True, max_length=255, verbose_name='genetic formula')),
                ('category', models.CharField(choices=[('antibiotics', 'Antibiotics'), ('analgesics', 'Analgesics'), ('antivirals', 'Antivirals'), ('supplements', 'Supplements'), ('cardiac', 'Cardiac Care')], max_length=50, verbose_name='clinical category')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='current stock')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price per unit')),
                ('expiry_date', models.DateField(verbose_name='expiry date')),
                ('batch_number', models.CharField(max_length=50, unique=True, verbose_name='batch ID')),
                ('reorder_level', models.IntegerField(default=10, help_text='Alert admin when stock falls below this.', verbose_name='reorder threshold')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hospital_pharmacy_inventory',
                'ordering': ['name'],
            },
        ),
    ]
