# Generated by Django 5.2.12 on 2026-03-27 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(help_text='Unique medical license number issued by PMDC (Pakistan).', max_length=50, unique=True, verbose_name='license number')),
                ('specialization', models.CharField(choices=[('general', 'General Physician'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('psychiatry', 'Psychiatry'), ('gynecology', 'Gynecology & Obstetrics'), ('ophthalmology', 'Ophthalmology'), ('ent', 'ENT (Ear, Nose & Throat)'), ('oncology', 'Oncology'), ('radiology', 'Radiology'), ('emergency', 'Emergency Medicine'), ('internal', 'Internal Medicine')], default='general', help_text='Medical specialization area.', max_length=30, verbose_name='specialization')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, help_text='Total years of medical practice.', verbose_name='years of experience')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee charged per appointment in Pakistani Rupees.', max_digits=8, verbose_name='consultation fee (PKR)')),
                ('available_days', models.JSONField(blank=True, default=list, help_text="List of days doctor is available. E.g. ['Monday', 'Wednesday'].", verbose_name='available days')),
                ('consultation_start_time', models.TimeField(blank=True, help_text='Daily consultation start time. E.g. 09:00.', null=True, verbose_name='consultation start time')),
                ('consultation_end_time', models.TimeField(blank=True, help_text='Daily consultation end time. E.g. 17:00.', null=True, verbose_name='consultation end time')),
                ('slot_duration_minutes', models.PositiveSmallIntegerField(default=30, help_text='Duration of each appointment slot in minutes.', verbose_name='slot duration (minutes)')),
                ('is_available', models.BooleanField(default=True, help_text='Uncheck to temporarily hide this doctor from booking.', verbose_name='is available')),
                ('bio', models.TextField(blank=True, default='', help_text='Short professional biography displayed to patients.', verbose_name='biography')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the doctor profile was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the doctor profile was last updated.')),
                ('user', models.OneToOneField(help_text='The user account associated with this doctor profile.', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'doctor',
                'verbose_name_plural': 'doctors',
                'db_table': 'hospital_doctors',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
