# Generated by Django 4.2.23 on 2026-03-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('general', 'General Physician'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('psychiatry', 'Psychiatry'), ('gynecology', 'Gynecology & Obstetrics'), ('ophthalmology', 'Ophthalmology'), ('ent', 'ENT (Ear, Nose & Throat)'), ('oncology', 'Oncology'), ('radiology', 'Radiology'), ('emergency', 'Emergency Medicine'), ('internal', 'Internal Medicine'), ('dentistry', 'Dentistry')], default='general', help_text='Medical specialization area.', max_length=30, verbose_name='specialization'),
        ),
    ]
