# Generated by Django 4.2.23 on 2026-03-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='clinic_address',
            field=models.CharField(blank=True, default='', help_text='Physical address of the clinic or hospital wing.', max_length=255, verbose_name='clinic address'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.CharField(blank=True, default='', help_text='Medical degree and institution (e.g. MBBS, King Edward Medical University).', max_length=255, verbose_name='education'),
        ),
    ]
